// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurpleBalls.Data;

namespace PurpleBalls.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190807101455_PlayerShirts")]
    partial class PlayerShirts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PurpleBalls.Data.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PurpleBalls.Data.Models.PlayerShirt", b =>
                {
                    b.Property<int>("PlayerShirtId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlayerId");

                    b.Property<string>("ShirtName");

                    b.Property<int>("ShirtNumber");

                    b.Property<string>("ShirtPrimary");

                    b.Property<string>("ShirtSecondary");

                    b.Property<int>("ShirtStyle");

                    b.HasKey("PlayerShirtId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerShirts");
                });

            modelBuilder.Entity("PurpleBalls.Data.Models.PlayerShirt", b =>
                {
                    b.HasOne("PurpleBalls.Data.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
